# Generated by Django 3.1.5 on 2021-01-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePasswords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepassword',
            name='password',
            field=models.CharField(max_length=10000),
        ),
    ]
