# Generated by Django 3.1.5 on 2021-02-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePasswords', '0002_auto_20210131_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepassword',
            name='website_url',
            field=models.CharField(max_length=120),
        ),
    ]
