# Generated by Django 3.1.5 on 2021-02-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePasswords', '0003_auto_20210204_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepassword',
            name='user',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
