# Generated by Django 3.1.5 on 2021-02-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitePasswords', '0005_auto_20210205_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepassword',
            name='website_url',
            field=models.URLField(max_length=120),
        ),
    ]
