repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2 # Use the latest Ruff version
    hooks:
      - id: ruff
        args: [--fix] # Auto-fix issues on commit
      - id: ruff-format
